package Nested.Exception;

public class TestFinallyBlock2 {

}
